import os

CLOUDBURST_USERNAME = os.getenv("CLOUDBURST_USERNAME")
CLOUDBURST_PASS = os.getenv("CLOUDBURST_PASS")
CLOUDBURST_HOST = os.getenv("CLOUDBURST_HOST")
SSH_PRIVATE_KEY_PASSWORD = os.getenv("SSH_PRIVATE_KEY_PASSWORD")
SSH_PKEY = os.getenv("SSH_PKEY")
NEO4J_URI = os.getenv("NEO4J_URI")
NEO4J_USERNAME = os.getenv("NEO4J_USERNAME")
NEO4J_PASSWORD = os.getenv("NEO4J_PASSWORD")
AURA_INSTANCENAME = os.getenv("AURA_INSTANCENAME")
URL_NODES = os.getenv("URL_NODES")
URL_EDGES = os.getenv("URL_EDGES")
